# 端口，固定的
server:
      port: 8080
# spring 配置
spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.1.199:3306/shiro
        username: root
        password: root
        # druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

freemarker:
    templateLoaderPath: "classpath:/template"
    properties:
        auto_import: "/common/commonMacros.ftl as macro"

ftlviewcofing:
    #静态工具配置
    staticAttrabutes:
        StringUtil: "freemarker.template.utility.StringUtil"
    #属性配置
    attrabutes:
        name:  ""
    cache: "false"
    cacheLimit: "0"
    suffix: ".ftl"
    contentType: "text/html;charset=UTF-8"
    requestContextAttribute: "request"
    exposeSpringMacroHelpers: "true"
    exposeRequestAttributes: "true"
    exposeSessionAttributes: "true"
    order: "0"
mybatis:
    #mapper接口包
    basePackage: "io.github.yanglong.demo.dao"
    #mapper接口注解类
    annotationClass: "io.github.yanglong.demo.config.mybatis.MyBatisRepository"
    #实体包
    typeAliasesPackage: "io.github.yanglong.demo.model"
    #mapper.xml位置
    mapperLocations: "classpath*:*/mapper/*Mapper.xml"