##！注意这里有坑
##！因为yml解析会自动转换类型，所以如果你用到Properties的方式来读取获取到的属性，非字符串的值会是null
# 端口，固定的
server:
      port: "8080"
# spring 配置
spring:
    datasource:
        name: "test"
        url: "jdbc:mysql://192.168.1.199:3306/shiro"
        username: "root"
        password: "root"
        # druid数据源
        type: "com.alibaba.druid.pool.DruidDataSource"
        driver-class-name: "com.mysql.jdbc.Driver"
        filters: "stat"
        maxActive: "20"
        initialSize: "1"
        maxWait: "60000"
        minIdle: "1"
        timeBetweenEvictionRunsMillis: "60000"
        minEvictableIdleTimeMillis: "300000"
        validationQuery: "select 'x'"
        testWhileIdle: "true"
        testOnBorrow: "false"
        testOnReturn: "false"
        poolPreparedStatements: "true"
        maxOpenPreparedStatements: "20"
    freemarker:
      template-loader-path: "classpath:templates"
      settings:
          auto_import: "/common/commonMacros.ftl as macro"
          tag_syntax: "auto_detect"
          template_update_delay: "0"
          defaultEncoding: "UTF-8"
          url_escaping_charset: "UTF-8"
          locale: "zhCN"
          date_format: "yyyy-MM-dd"
          datetime_format: "yyyy-MM-dd HH:mm:ss"
          time_format: "HH:mm:ss"
          number_format: "0.######"
          whitespace_stripping: "true"
#freemarker视图属性及自定义宏设置
ftlviewcofing:
    #静态工具配置
    staticAttributes:
        StringUtil: "freemarker.templates.utility.StringUtil"
    #属性配置
    #attributes:
        #name: value
    cache: "false"
    cacheLimit: "0"
    prefix: ""
    suffix: ".ftl"
    contentType: "text/html;charset=UTF-8"
    requestContextAttribute: "request"
    exposeSpringMacroHelpers: "true"
    exposeRequestAttributes: "true"
    exposeSessionAttributes: "true"
    order: "0"
mybatis:
    #mapper接口包
    basePackage: "io.github.yanglong.demo.dao"
    #mapper接口注解类
    annotationClass: "io.github.yanglong.demo.config.mybatis.MyBatisRepository"
    #实体包
    typeAliasesPackage: "io.github.yanglong.demo.model"
    #mapper.xml位置
    mapperLocations: "classpath:/mapper/*Mapper.xml"